// src/translate/getWordMeaning.ts

import type { LanguageCode } from "../storage";

export type WordMeaningResult = {
  word: string;
  meaning: string;
  fromCache: boolean;
};

type PairKey = `${LanguageCode}->${LanguageCode}`;

const WORD_MEANINGS: Partial<Record<PairKey, Record<string, string>>> = {
  // ══════════════════════════════════════════════════════
  // EN → ES
  // ══════════════════════════════════════════════════════
  "en->es": {
    // saludos
    hello: "hola",
    hi: "hola",
    hey: "oye",
    goodbye: "adiós",
    bye: "chau",
    welcome: "bienvenido",
    greetings: "saludos",

    // pronombres
    i: "yo",
    you: "vos",
    he: "él",
    she: "ella",
    we: "nosotros",
    they: "ellos",
    it: "eso",
    me: "mí",
    my: "mi",
    your: "tu",
    his: "su",
    her: "su",
    our: "nuestro",
    their: "su",

    // verbos
    be: "ser",
    am: "soy",
    is: "es",
    are: "son",
    was: "era",
    were: "eran",
    have: "tener",
    has: "tiene",
    had: "tenía",
    do: "hacer",
    does: "hace",
    did: "hizo",
    will: "va a",
    would: "querría",
    can: "poder",
    could: "podría",
    should: "debería",
    must: "deber",
    may: "quizás",
    might: "podría",
    need: "necesitar",
    want: "querer",
    like: "gustar",
    love: "amar",
    hate: "odiar",
    think: "pensar",
    know: "saber",
    see: "ver",
    look: "mirar",
    watch: "ver",
    hear: "escuchar",
    listen: "escuchar",
    feel: "sentir",
    seem: "parecer",
    become: "volverse",
    get: "obtener",
    give: "dar",
    take: "tomar",
    make: "hacer",
    put: "poner",
    say: "decir",
    tell: "contar",
    ask: "preguntar",
    answer: "responder",
    find: "encontrar",
    keep: "mantener",
    let: "dejar",
    show: "mostrar",
    try: "intentar",
    use: "usar",
    help: "ayudar",
    call: "llamar",
    come: "venir",
    go: "ir",
    run: "correr",
    walk: "caminar",
    talk: "hablar",
    speak: "hablar",
    work: "trabajar",
    play: "jugar",
    live: "vivir",
    move: "mover",
    meet: "conocer",
    leave: "salir",
    start: "empezar",
    begin: "comenzar",
    stop: "parar",
    finish: "terminar",
    end: "terminar",
    send: "enviar",
    receive: "recibir",
    read: "leer",
    write: "escribir",
    learn: "aprender",
    teach: "enseñar",
    study: "estudiar",
    understand: "entender",
    remember: "recordar",
    forget: "olvidar",
    wait: "esperar",
    hope: "desear",
    change: "cambiar",
    open: "abrir",
    close: "cerrar",
    eat: "comer",
    drink: "beber",
    sleep: "dormir",
    wake: "despertar",
    buy: "comprar",
    sell: "vender",
    pay: "pagar",
    travel: "viajar",
    visit: "visitar",
    join: "unirse",
    share: "compartir",
    create: "crear",
    build: "construir",
    lose: "perder",
    win: "ganar",
    choose: "elegir",
    decide: "decidir",
    happen: "ocurrir",
    grow: "crecer",
    enjoy: "disfrutar",
    miss: "extrañar",
    return: "volver",
    stay: "quedarse",
    sit: "sentarse",
    stand: "pararse",
    bring: "traer",
    carry: "llevar",
    hold: "sostener",
    follow: "seguir",
    reach: "alcanzar",
    save: "guardar",
    set: "establecer",
    cut: "cortar",
    draw: "dibujar",
    sing: "cantar",
    dance: "bailar",

    // sustantivos
    thing: "cosa",
    way: "camino",
    day: "día",
    time: "tiempo",
    year: "año",
    month: "mes",
    week: "semana",
    hour: "hora",
    minute: "minuto",
    man: "hombre",
    woman: "mujer",
    people: "gente",
    person: "persona",
    child: "niño",
    friend: "amigo",
    family: "familia",
    home: "hogar",
    house: "casa",
    school: "escuela",
    city: "ciudad",
    country: "país",
    world: "mundo",
    life: "vida",
    hand: "mano",
    eye: "ojo",
    head: "cabeza",
    face: "cara",
    body: "cuerpo",
    heart: "corazón",
    name: "nombre",
    word: "palabra",
    place: "lugar",
    part: "parte",
    group: "grupo",
    kind: "tipo",
    type: "tipo",
    area: "área",
    door: "puerta",
    room: "habitación",
    street: "calle",
    water: "agua",
    food: "comida",
    money: "dinero",
    book: "libro",
    language: "idioma",
    question: "pregunta",
    idea: "idea",
    story: "historia",
    night: "noche",
    morning: "mañana",
    evening: "tarde",
    today: "hoy",
    tomorrow: "mañana (día)",
    yesterday: "ayer",
    music: "música",
    movie: "película",
    game: "juego",
    sport: "deporte",
    trip: "viaje",
    job: "trabajo",
    plan: "plan",
    dream: "sueño",
    news: "noticias",
    phone: "teléfono",
    message: "mensaje",
    photo: "foto",
    number: "número",
    problem: "problema",
    reason: "razón",
    moment: "momento",
    feeling: "sentimiento",
    hobby: "pasatiempo",
    hobbies: "pasatiempos",
    culture: "cultura",
    interest: "interés",
    color: "color",
    town: "pueblo",
    park: "parque",
    beach: "playa",
    mountain: "montaña",
    river: "río",
    sea: "mar",
    sky: "cielo",
    sun: "sol",
    moon: "luna",
    star: "estrella",
    tree: "árbol",
    flower: "flor",
    dog: "perro",
    cat: "gato",
    bird: "pájaro",
    car: "auto",
    train: "tren",
    bus: "colectivo",
    plane: "avión",
    restaurant: "restaurante",
    coffee: "café",
    tea: "té",
    bread: "pan",
    fruit: "fruta",
    meat: "carne",

    // adjetivos
    nice: "agradable",
    good: "bueno",
    great: "genial",
    bad: "malo",
    big: "grande",
    small: "pequeño",
    long: "largo",
    short: "corto",
    new: "nuevo",
    old: "viejo",
    young: "joven",
    first: "primero",
    last: "último",
    high: "alto",
    low: "bajo",
    right: "correcto",
    wrong: "incorrecto",
    true: "verdadero",
    false: "falso",
    real: "real",
    free: "libre",
    easy: "fácil",
    hard: "difícil",
    important: "importante",
    different: "diferente",
    same: "igual",
    happy: "feliz",
    sad: "triste",
    funny: "gracioso",
    interesting: "interesante",
    beautiful: "hermoso",
    cool: "genial",
    hot: "caliente",
    cold: "frío",
    fast: "rápido",
    slow: "lento",
    sure: "seguro",
    ready: "listo",
    alone: "solo",
    together: "juntos",
    early: "temprano",
    late: "tarde",
    often: "seguido",
    always: "siempre",
    never: "nunca",
    sometimes: "a veces",
    possible: "posible",
    special: "especial",
    favorite: "favorito",
    typical: "típico",
    amazing: "increíble",
    wonderful: "maravilloso",
    terrible: "terrible",
    perfect: "perfecto",
    simple: "simple",
    popular: "popular",
    local: "local",

    // conectores / preposiciones
    and: "y",
    or: "o",
    but: "pero",
    so: "entonces",
    because: "porque",
    if: "si",
    when: "cuando",
    where: "dónde",
    what: "qué",
    who: "quién",
    how: "cómo",
    why: "por qué",
    which: "cuál",
    that: "que",
    this: "esto",
    these: "estos",
    those: "esos",
    about: "sobre",
    after: "después",
    before: "antes",
    during: "durante",
    for: "para",
    from: "de",
    in: "en",
    of: "de",
    on: "sobre",
    at: "a las",
    by: "por",
    to: "a",
    with: "con",
    without: "sin",
    between: "entre",
    through: "a través",
    over: "sobre",
    under: "bajo",
    up: "arriba",
    down: "abajo",
    out: "fuera",
    than: "que",
    then: "entonces",
    also: "también",
    just: "solo",
    very: "muy",
    more: "más",
    most: "el más",
    much: "mucho",
    many: "muchos",
    few: "pocos",
    little: "poco",
    all: "todo",
    any: "cualquier",
    some: "algo",
    not: "no",
    only: "solo",
    well: "bien",
    still: "todavía",
    again: "otra vez",
    back: "atrás",
    now: "ahora",
    already: "ya",
    yet: "todavía",
    here: "aquí",
    there: "allá",
    really: "realmente",
    too: "también",
    enough: "suficiente",
    even: "incluso",
    both: "ambos",
    other: "otro",
    each: "cada",
    every: "cada",
  },

  // ══════════════════════════════════════════════════════
  // ES → EN
  // ══════════════════════════════════════════════════════
  "es->en": {
    hola: "hello",
    chau: "bye",
    gracias: "thanks",
    favor: "please",
    perdón: "sorry",
    si: "yes",
    no: "no",
    yo: "I",
    vos: "you",
    él: "he",
    ella: "she",
    nosotros: "we",
    ellos: "they",
    ser: "to be",
    estar: "to be",
    soy: "I am",
    estoy: "I am",
    es: "is",
    son: "are",
    tener: "to have",
    tengo: "I have",
    tiene: "has",
    hacer: "to do",
    ir: "to go",
    voy: "I go",
    venir: "to come",
    hablar: "to speak",
    querer: "to want",
    poder: "can",
    saber: "to know",
    conocer: "to know",
    ver: "to see",
    mirar: "to look",
    escuchar: "to listen",
    comer: "to eat",
    beber: "to drink",
    dormir: "to sleep",
    vivir: "to live",
    trabajar: "to work",
    estudiar: "to study",
    aprender: "to learn",
    jugar: "to play",
    viajar: "to travel",
    ciudad: "city",
    país: "country",
    mundo: "world",
    vida: "life",
    amigo: "friend",
    familia: "family",
    casa: "house",
    trabajo: "job",
    tiempo: "time",
    día: "day",
    noche: "night",
    mañana: "morning",
    comida: "food",
    agua: "water",
    idioma: "language",
    música: "music",
    película: "movie",
    deporte: "sport",
    bueno: "good",
    malo: "bad",
    grande: "big",
    pequeño: "small",
    nuevo: "new",
    viejo: "old",
    feliz: "happy",
    triste: "sad",
    fácil: "easy",
    difícil: "hard",
    bonito: "nice",
    lindo: "cute",
    genial: "great",
    interesante: "interesting",
    importante: "important",
    gente: "people",
    persona: "person",
    nombre: "name",
    lugar: "place",
    idea: "idea",
    pregunta: "question",
    historia: "story",
    hoy: "today",
    ayer: "yesterday",
    siempre: "always",
    nunca: "never",
    también: "also",
    pero: "but",
    porque: "because",
    cuando: "when",
    donde: "where",
    cómo: "how",
    qué: "what",
    quién: "who",
  },

  // ══════════════════════════════════════════════════════
  // RU → ES
  // ══════════════════════════════════════════════════════
  "ru->es": {
    привет: "hola",
    пока: "chau",
    спасибо: "gracias",
    пожалуйста: "por favor",
    да: "sí",
    нет: "no",
    я: "yo",
    ты: "vos",
    он: "él",
    она: "ella",
    мы: "nosotros",
    они: "ellos",
    имя: "nombre",
    город: "ciudad",
    страна: "país",
    друг: "amigo",
    семья: "familia",
    дом: "casa",
    работа: "trabajo",
    язык: "idioma",
    музыка: "música",
    фильм: "película",
    спорт: "deporte",
    хорошо: "bien",
    плохо: "mal",
    большой: "grande",
    маленький: "pequeño",
    новый: "nuevo",
    старый: "viejo",
    красивый: "bonito",
    интересный: "interesante",
    как: "cómo",
    где: "dónde",
    когда: "cuándo",
    почему: "por qué",
    что: "qué",
    кто: "quién",
    есть: "hay",
    много: "mucho",
    мало: "poco",
    все: "todos",
    всё: "todo",
    время: "tiempo",
    день: "día",
    ночь: "noche",
    утро: "mañana",
    еда: "comida",
    вода: "agua",
    жить: "vivir",
    любить: "amar",
    знать: "saber",
    говорить: "hablar",
    идти: "ir",
    хотеть: "querer",
  },

  // ══════════════════════════════════════════════════════
  // DE → ES
  // ══════════════════════════════════════════════════════
  "de->es": {
    hallo: "hola",
    hi: "hola",
    tschüss: "chau",
    danke: "gracias",
    bitte: "por favor",
    ja: "sí",
    nein: "no",
    ich: "yo",
    du: "vos",
    er: "él",
    sie: "ella",
    wir: "nosotros",
    ihr: "ustedes",
    sein: "ser",
    haben: "tener",
    machen: "hacer",
    gehen: "ir",
    kommen: "venir",
    sprechen: "hablar",
    wollen: "querer",
    können: "poder",
    wissen: "saber",
    sehen: "ver",
    hören: "escuchar",
    essen: "comer",
    trinken: "beber",
    schlafen: "dormir",
    leben: "vivir",
    arbeiten: "trabajar",
    lernen: "aprender",
    spielen: "jugar",
    reisen: "viajar",
    lieben: "amar",
    denken: "pensar",
    stadt: "ciudad",
    land: "país",
    welt: "mundo",
    freund: "amigo",
    familie: "familia",
    haus: "casa",
    arbeit: "trabajo",
    sprache: "idioma",
    musik: "música",
    film: "película",
    sport: "deporte",
    name: "nombre",
    gut: "bueno",
    schlecht: "malo",
    groß: "grande",
    klein: "pequeño",
    neu: "nuevo",
    alt: "viejo",
    glücklich: "feliz",
    traurig: "triste",
    einfach: "fácil",
    schwierig: "difícil",
    schön: "bonito",
    interessant: "interesante",
    wichtig: "importante",
    wie: "cómo",
    was: "qué",
    wer: "quién",
    wo: "dónde",
    wann: "cuándo",
    warum: "por qué",
    und: "y",
    oder: "o",
    aber: "pero",
    weil: "porque",
    heute: "hoy",
    morgen: "mañana",
    gestern: "ayer",
    immer: "siempre",
    nie: "nunca",
    auch: "también",
  },
};

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

function normalize(s: string): string {
  return (s ?? "").trim().toLowerCase();
}

function lookupLocal(
  word: string,
  from: LanguageCode,
  to: LanguageCode
): string | null {
  // Directo
  const direct = WORD_MEANINGS[`${from}->${to}` as PairKey];
  if (direct) {
    const hit = direct[normalize(word)];
    if (hit != null) return hit;
  }

  // Pivot: from→en→to
  if (from !== "en" && to !== "en") {
    const toEn = WORD_MEANINGS[`${from}->en` as PairKey];
    if (toEn) {
      const pivot = toEn[normalize(word)];
      if (pivot) {
        const firstPivot = pivot.split(/[\s/,]+/)[0].trim();
        const enTo = WORD_MEANINGS[`en->${to}` as PairKey];
        if (enTo) {
          const final = enTo[normalize(firstPivot)];
          if (final) return final;
        }
        return pivot;
      }
    }
  }

  return null;
}

// ─────────────────────────────────────────────────────────────
// Export principal
// ─────────────────────────────────────────────────────────────

export async function getWordMeaning(
  word: string,
  fromLang: LanguageCode,
  toLang: LanguageCode
): Promise<WordMeaningResult> {
  const trimmed = (word ?? "").trim();

  if (!trimmed || fromLang === toLang) {
    return { word: trimmed, meaning: trimmed, fromCache: true };
  }

  // 1) Diccionario local
  const local = lookupLocal(trimmed, fromLang, toLang);
  if (local !== null) {
    return { word: trimmed, meaning: local, fromCache: true };
  }

  // 2) API remota → primera palabra solo
  try {
    const { apiTranslateText } = await import("./translatorApi");
    const raw = await apiTranslateText({ text: trimmed, from: fromLang, to: toLang });

    const firstToken = (raw ?? "")
      .trim()
      .split(/[\s,.\-–:;/()\[\]]+/)
      .map((t) => t.trim())
      .filter((t) => t.length > 0)[0];

    return {
      word: trimmed,
      meaning: firstToken ?? raw.trim() ?? "—",
      fromCache: false,
    };
  } catch {
    return { word: trimmed, meaning: "—", fromCache: true };
  }
}